### ISSUE TITLE
Unsupported Version 9

### ISSUE THREAD

**Issue by SwissBorn2Frag** [Qowyn/ark-savegame-toolkit#5]
Please change the following in qowyn/ark/ArkSavegame.java:

**Line 168:**
**From:**
    } else if (saveVersion == 7) {
**To:**
    } else if (saveVersion >= 7) {

Unfortunately im not able to build it myself because of Maven Errors and missing knowhow about it. I can't build a normal executable jar too because Eclipse seems to doesn't find the main method.

**Comment by SwissBorn2Frag** [comment]
This time it seems like it needs more than only a version change. The following Exception is thrown when you replace the check with >=7:

Sep 07, 2017 1:03:23 PM qowyn.ark.ArkArchive getString
SCHWERWIEGEND: Trying to read 335572069 bytes at 73 with just 49672128 bytes left
java.nio.BufferOverflowException
        at qowyn.ark.ArkArchive.getString(ArkArchive.java:110)
        at qowyn.ark.ArkSavegame.readBinaryDataFiles(ArkSavegame.java:205)
        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:147)
        at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:90)
        at qowyn.ark.tools.CreatureListCommands.listImpl(CreatureListCommands.java:109)
        at qowyn.ark.tools.CreatureListCommands.tamed(CreatureListCommands.java:62)
        at qowyn.ark.tools.App.main(App.java:117)

**Comment by SwissBorn2Frag** [comment]
Unfortunately i do not have enough java knowhow to fix all the buffer/string/overflow/underflow problems. 
Thanks wildcard for messing all up one week after release!

**Comment by Qowyn** [comment]
Completly fixed with v0.8.0
